// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TinyDrive.Infrastructure.Data;

#nullable disable

namespace TinyDrive.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260201003307_Add_IsDeleted_To_Index")]
    partial class Add_IsDeleted_To_Index
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TinyDrive.Domain.Entities.Node", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContentType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("content_type");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at_utc");

                    b.Property<string>("Extension")
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasColumnName("extension");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsFolder")
                        .HasColumnType("boolean")
                        .HasColumnName("is_folder");

                    b.Property<DateTime?>("LastModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified_at_utc");

                    b.Property<string>("MaterializedPath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("materialized_path");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    b.Property<long?>("Size")
                        .HasColumnType("bigint")
                        .HasColumnName("size");

                    b.Property<int?>("UploadStatus")
                        .HasColumnType("integer")
                        .HasColumnName("upload_status");

                    b.HasKey("Id")
                        .HasName("pk_nodes");

                    b.HasIndex("MaterializedPath")
                        .HasDatabaseName("ix_nodes_materialized_path");

                    b.HasIndex("ParentId", "Name", "Extension", "IsFolder", "IsDeleted")
                        .IsUnique()
                        .HasDatabaseName("ix_nodes_parent_id_name_extension_is_folder_is_deleted");

                    b.ToTable("nodes", (string)null);
                });

            modelBuilder.Entity("TinyDrive.Domain.Entities.Node", b =>
                {
                    b.HasOne("TinyDrive.Domain.Entities.Node", null)
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_nodes_nodes_parent_id");
                });
#pragma warning restore 612, 618
        }
    }
}
