// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TinyDrive.Infrastructure.Data;

#nullable disable

namespace TinyDrive.Infrastructure.Migrations.Application
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260110183107_Add_Node")]
    partial class Add_Node
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TinyDrive.Domain.Nodes.Node", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("bytea")
                        .HasColumnName("id");

                    b.Property<string>("ContentType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("content_type");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Extension")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("extension");

                    b.Property<bool>("IsFolder")
                        .HasColumnType("boolean")
                        .HasColumnName("is_folder");

                    b.Property<DateTime?>("LastModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified_at_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<byte[]>("ParentId")
                        .HasColumnType("bytea")
                        .HasColumnName("parent_id");

                    b.Property<long?>("Size")
                        .IsRequired()
                        .HasColumnType("bigint")
                        .HasColumnName("size");

                    b.HasKey("Id")
                        .HasName("pk_nodes");

                    b.HasIndex("ParentId", "Name", "Extension")
                        .IsUnique()
                        .HasDatabaseName("ix_nodes_parent_id_name_extension");

                    b.ToTable("nodes", "public");
                });

            modelBuilder.Entity("TinyDrive.Domain.Nodes.Node", b =>
                {
                    b.HasOne("TinyDrive.Domain.Nodes.Node", null)
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_nodes_nodes_parent_id");
                });
#pragma warning restore 612, 618
        }
    }
}
